image:
  file: .gitpod.Dockerfile

tasks:
  - name: spring-data-cassandra
    command: |
      cd todobackend-springdata && mvn clean package install -Dmaven.test.skip=true
ports:
  - port: 8080
    onOpen: open-browser 
    visibility: public

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false

vscode:
  extensions:
    # Lombok
    - GabrielBB.vscode-lombok
    # Java
    - vscjava.vscode-java-pack
    # Spring Boot
    - Pivotal.vscode-boot-dev-pack
